version: '3.7'

services:
  users-db:
    build:
      context: ./services/users/app/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile.dev
    command: flask run -h 0.0.0.0
    volumes:
      - type: bind
        source: ./services/users
        target: /usr/src/users
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE=postgres
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - SQL_HOST=users-db
      - SQL_PORT=5432
    expose:
      - 5000
    depends_on:
      - users-db

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8000:80
    depends_on:
      - users
