version: '3.7'

services:
  users-db:
    build:
      context: ./services/users/app/db
      dockerfile: Dockerfile
    env_file: .env.db
    expose:
      - 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
        volume:
          nocopy: true

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - "home.app.users.__init__:create_app()"
    depends_on:
      - users-db
    env_file: .env
    ports:
      - 5000:5000

volumes:
  postgres_data:
