# base image
FROM python:3.8.1-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /usr/src/users

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# add and install requirements
COPY ./requirements.txt /usr/src/users/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/users/entrypoint.sh
RUN chmod +x /usr/src/users/entrypoint.sh

# add app
COPY . /usr/src/users

RUN pip install --editable /usr/src/users

# run server
CMD ["/usr/src/users/entrypoint.sh"]